---
- name: Create temporary directory
  win_file:
    path: "{{ openssh_temporary_dir }}"
    state: directory

- name: Get openssh for windows release
  win_get_url:
    url: "{{ openssh_download_url }}"
    dest: "{{ openssh_temporary_dir }}\\openssh.zip"
    force: no

- name: Unzip openssh in extraction dir
  win_unzip:
    src: "{{ openssh_temporary_dir }}\\openssh.zip"
    dest: "{{ openssh_extract_dir }}"
    creates: "{{ openssh_extract_dir }}"

- name: Check if ssh private key exists
  win_stat: path="{{ openssh_extract_dir }}\\{{ openssh_archive_name }}\\ssh_host_dsa_key"
  register: private_key

- name: Copy installation script
  win_template:
    src: "{{ role_path }}/templates/install-openssh.ps1.j2"
    dest: "C:\\install-openssh.ps1"
  when: not private_key.stat.exists

- name: Run installation script
  raw: "C:\\install-openssh.ps1"
  when: not private_key.stat.exists

- name: Deploy ssh server configuration
  win_template:
    src: "{{ role_path }}/templates/sshd_config.j2"
    dest: "{{ openssh_extract_dir }}\\{{ openssh_archive_name }}\\sshd_config"
  notify:
    - restart sshd
